version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore

  - package-ecosystem: composer
    directory: "/container-demo"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - php
    commit-message:
      prefix: chore
