#!/usr/bin/env python3
"""
Generates a beginner-friendly PDF explaining the ghazdo-to-ado.json workflow
step by step, with the actual JSON snippets and plain-English explanations.
"""

from fpdf import FPDF
import os, json, textwrap

class ExplainerPDF(FPDF):
    BLUE = (0, 120, 212)
    DARK = (30, 30, 30)
    GRAY = (100, 100, 100)
    WHITE = (255, 255, 255)
    LIGHT_BG = (245, 245, 245)
    GREEN = (16, 124, 16)
    ORANGE = (200, 100, 0)
    RED = (200, 30, 30)
    PURPLE = (100, 50, 150)

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.GRAY)
        self.cell(0, 6, "GHAzDO-to-ADO Workflow Explainer", align="L")
        self.cell(0, 6, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.GRAY)
        self.cell(0, 10, "Confidential - Learfield Demo | Generated by Copilot CLI", align="C")

    def title_page(self):
        self.add_page()
        self.ln(40)
        self.set_font("Helvetica", "B", 28)
        self.set_text_color(*self.BLUE)
        self.cell(0, 14, "GHAzDO-to-ADO Workflow", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_font("Helvetica", "B", 22)
        self.cell(0, 12, "Step-by-Step Explainer", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)
        self.set_font("Helvetica", "", 13)
        self.set_text_color(*self.DARK)
        self.cell(0, 8, "A Beginner-Friendly Guide to the Logic App Workflow", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(20)
        self.set_font("Helvetica", "", 11)
        self.set_text_color(*self.GRAY)
        info = [
            ("File:", "ghazdo-to-ado.json"),
            ("Lines:", "218"),
            ("Purpose:", "Auto-create & auto-close ADO work items from GHAzDO alerts"),
            ("Logic App:", "ghas-ado-sync-demo2 (Azure Consumption tier)"),
            ("ADO Org:", "brandsafway1 / brandsafway_Engg"),
        ]
        for label, val in info:
            self.set_font("Helvetica", "B", 11)
            self.cell(40, 7, label, align="R")
            self.set_font("Helvetica", "", 11)
            self.cell(0, 7, f"  {val}", new_x="LMARGIN", new_y="NEXT")
        self.ln(30)
        self.set_font("Helvetica", "I", 9)
        self.cell(0, 6, "March 2026", align="C")

    def section_header(self, num, title):
        if self.get_y() > 240:
            self.add_page()
        self.ln(6)
        self.set_fill_color(*self.BLUE)
        self.set_text_color(*self.WHITE)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, f"  Step {num}: {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_text_color(*self.DARK)

    def sub_header(self, title, color=None):
        if self.get_y() > 255:
            self.add_page()
        c = color or self.BLUE
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*c)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*self.DARK)
        self.ln(1)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.DARK)
        self.multi_cell(0, 5.5, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def code_block(self, code, max_lines=30):
        self.set_font("Courier", "", 8)
        self.set_fill_color(*self.LIGHT_BG)
        self.set_text_color(50, 50, 50)
        lines = code.strip().split("\n")[:max_lines]
        for line in lines:
            safe = line.replace("\u2019", "'").replace("\u2018", "'").replace("\u201c", '"').replace("\u201d", '"').replace("\u2014", "--").replace("\u2013", "-").replace("\u2026", "...").replace("\u2022", "*").replace("\u00b7", "*").replace("\u2192", "->").replace("\u2190", "<-")
            if self.get_y() > 275:
                self.add_page()
                self.set_font("Courier", "", 8)
                self.set_fill_color(*self.LIGHT_BG)
                self.set_text_color(50, 50, 50)
            self.cell(0, 4.5, f"  {safe[:120]}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)
        self.set_text_color(*self.DARK)

    def callout(self, text, icon="INFO", color=None):
        c = color or self.BLUE
        if self.get_y() > 260:
            self.add_page()
        self.set_fill_color(c[0], c[1], c[2])
        self.rect(10, self.get_y(), 3, 12, "F")
        self.set_x(16)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*c)
        self.cell(15, 6, f"{icon}:")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self.DARK)
        safe = text.replace("\u2019", "'").replace("\u2018", "'").replace("\u201c", '"').replace("\u201d", '"').replace("\u2014", "--").replace("\u2192", "->")
        self.multi_cell(170, 5, safe, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def table_row(self, cells, header=False):
        if self.get_y() > 270:
            self.add_page()
        if header:
            self.set_fill_color(*self.BLUE)
            self.set_text_color(*self.WHITE)
            self.set_font("Helvetica", "B", 9)
        else:
            self.set_fill_color(*self.LIGHT_BG)
            self.set_text_color(*self.DARK)
            self.set_font("Helvetica", "", 9)
        widths = [50, 140] if len(cells) == 2 else [35, 55, 100]
        for i, c in enumerate(cells):
            safe = str(c).replace("\u2019", "'").replace("\u2018", "'")
            self.cell(widths[i], 7, f" {safe}", border=1, fill=True)
        self.ln()

    def diagram(self, lines):
        self.set_font("Courier", "B", 9)
        self.set_text_color(*self.BLUE)
        for line in lines:
            if self.get_y() > 275:
                self.add_page()
                self.set_font("Courier", "B", 9)
                self.set_text_color(*self.BLUE)
            safe = line.replace("\u2192", "->").replace("\u2190", "<-").replace("\u2502", "|").replace("\u2500", "-").replace("\u250c", "+").replace("\u2510", "+").replace("\u2514", "+").replace("\u2518", "+")
            self.cell(0, 5, safe, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)
        self.set_text_color(*self.DARK)

def build_pdf():
    pdf = ExplainerPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── TITLE PAGE ──
    pdf.title_page()

    # ── TABLE OF CONTENTS ──
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*pdf.BLUE)
    pdf.cell(0, 12, "Table of Contents", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    toc = [
        ("1", "The Big Picture - What Does This Workflow Do?"),
        ("2", "Schema & Content Version - The File Header"),
        ("3", "Parameters - Configurable Settings"),
        ("4", "The Trigger - How the Workflow Starts"),
        ("5", "Field Extractors - Pulling Data from the Webhook"),
        ("6", "Building the Unique Tag (Deduplication Key)"),
        ("7", "Building the Work Item Title"),
        ("8", "Building the Tags String"),
        ("9", "Building the HTML Description"),
        ("10", "Deciding: Create or Close? (Event Type Check)"),
        ("11", "CREATE Path - Making a New Work Item"),
        ("12", "CLOSE Path - Auto-Closing Resolved Alerts"),
        ("13", "Complete Data Flow Diagram"),
        ("14", "Quick Reference Cheat Sheet"),
    ]
    for num, title in toc:
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*pdf.DARK)
        pdf.cell(12, 7, num + ".")
        pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ═══════════════════════════════════════════════════════════
    # STEP 1: THE BIG PICTURE
    # ═══════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_header("1", "The Big Picture - What Does This Workflow Do?")

    pdf.body_text(
        "Imagine you have a code repository in Azure DevOps (ADO), and Azure's security scanner "
        "(called GHAzDO - GitHub Advanced Security for Azure DevOps) finds a problem. Maybe someone "
        "accidentally committed a password, or there's a vulnerable library in your code.\n\n"
        "Right now, the security team has to manually check the security dashboard, then manually "
        "create a work item (like a ticket) in ADO Boards to track the fix. This is slow and error-prone.\n\n"
        "THIS WORKFLOW automates that entire process:"
    )

    pdf.diagram([
        "  +-------------------+     +-----------------+     +------------------+",
        "  | GHAzDO detects a  | --> | ADO Service Hook | --> | Logic App runs   |",
        "  | security alert    |     | sends webhook    |     | this workflow    |",
        "  +-------------------+     +-----------------+     +------------------+",
        "                                                            |",
        "                                        +-------------------+-------------------+",
        "                                        |                                       |",
        "                                  [Alert Created?]                     [Alert Resolved?]",
        "                                        |                                       |",
        "                                        v                                       v",
        "                              +------------------+                   +------------------+",
        "                              | Create ADO Work  |                   | Close ADO Work   |",
        "                              | Item (Issue)     |                   | Item (Done)      |",
        "                              +------------------+                   +------------------+",
    ])

    pdf.body_text(
        "In plain English: When a new vulnerability is found, the workflow automatically creates a "
        "work item with all the details. When the vulnerability is fixed/resolved, it automatically "
        "closes that work item. No human intervention needed!"
    )

    pdf.callout(
        "This is a 'Consumption' tier Logic App - you only pay per execution (fractions of a cent). "
        "It costs almost nothing to run.",
        "COST", pdf.GREEN
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 2: SCHEMA & CONTENT VERSION
    # ═══════════════════════════════════════════════════════════
    pdf.section_header("2", "Schema & Content Version - The File Header")

    pdf.body_text(
        "Every Logic App workflow JSON starts with two boilerplate lines. Think of them like the "
        "DOCTYPE declaration in an HTML file - they tell Azure what kind of file this is."
    )

    pdf.code_block("""{
  "$schema": "https://schema.management.azure.com/providers/.../workflowdefinition.json#",
  "contentVersion": "1.0.0.0",
  ...
}""")

    pdf.table_row(["Field", "What It Means"], header=True)
    pdf.table_row(["$schema", "Points to Microsoft's official schema so Azure can validate the JSON"])
    pdf.table_row(["contentVersion", "Your version number (like a 'save number'). Always 1.0.0.0 to start"])

    pdf.callout(
        "You never need to change these. Azure adds them automatically when you create a Logic App.",
        "TIP", pdf.GREEN
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 3: PARAMETERS
    # ═══════════════════════════════════════════════════════════
    pdf.section_header("3", "Parameters - Configurable Settings")

    pdf.body_text(
        "Parameters are like variables you set ONCE when you deploy the Logic App. They let you "
        "reuse the same workflow for different ADO organizations without editing the JSON."
    )

    pdf.code_block(""""parameters": {
  "adoOrganization": { "type": "String" },
  "adoProject":      { "type": "String" },
  "adoPat":          { "type": "SecureString" },
  "workItemType":    { "type": "String", "defaultValue": "Issue" }
}""")

    pdf.table_row(["Parameter", "Type", "Purpose"], header=True)
    pdf.table_row(["adoOrganization", "String", "Your ADO org name (e.g. 'brandsafway1')"])
    pdf.table_row(["adoProject", "String", "The ADO project name (e.g. 'brandsafway_Engg')"])
    pdf.table_row(["adoPat", "SecureString", "Personal Access Token for ADO API authentication"])
    pdf.table_row(["workItemType", "String", "Type of work item to create (default: 'Issue')"])

    pdf.callout(
        "adoPat is marked as 'SecureString' - this means Azure encrypts it at rest and never "
        "shows it in logs or run history. Always use SecureString for secrets!",
        "SECURITY", pdf.RED
    )

    pdf.body_text(
        "To reference a parameter later in the workflow, you use this syntax:\n"
        "  parameters('adoOrganization')  ->  returns 'brandsafway1'\n\n"
        "Think of it like calling a function that returns the stored value."
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 4: THE TRIGGER
    # ═══════════════════════════════════════════════════════════
    pdf.section_header("4", "The Trigger - How the Workflow Starts")

    pdf.body_text(
        "A trigger is the 'starting gun' for the workflow. This Logic App uses an HTTP Request "
        "trigger, which means it exposes a URL (like a webhook). When anything sends an HTTP POST "
        "to that URL, the workflow runs."
    )

    pdf.code_block(""""triggers": {
  "When_a_GHAzDO_alert_is_received": {
    "type": "Request",
    "kind": "Http",
    "inputs": { "schema": {} }
  }
}""")

    pdf.sub_header("How It Works:")
    pdf.body_text(
        "1. Azure generates a unique URL for this trigger (with a secret signature in the URL)\n"
        "2. You paste that URL into ADO's Service Hook configuration\n"
        "3. When GHAzDO detects a vulnerability, ADO sends a POST request to that URL\n"
        "4. The Logic App wakes up and runs the workflow with the POST body as input\n\n"
        "The 'schema: {}' means we accept ANY JSON body (no validation). This is flexible but "
        "means we need to use 'coalesce()' later to handle missing fields safely."
    )

    pdf.callout(
        "The trigger URL looks like: https://prod-33.eastus.logic.azure.com:443/workflows/.../"
        "triggers/When_a_GHAzDO_alert_is_received/paths/invoke?api-version=...&sig=...",
        "URL", pdf.BLUE
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 5: FIELD EXTRACTORS
    # ═══════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_header("5", "Field Extractors - Pulling Data from the Webhook")

    pdf.body_text(
        "When the webhook arrives, it contains a big JSON payload with all the alert details. "
        "The first thing the workflow does is extract each piece of data into its own named variable. "
        "Think of it like unpacking a shipping box and labeling each item.\n\n"
        "Each 'Compose' action takes one piece of data from the webhook and saves it with a name."
    )

    # EventType
    pdf.sub_header("5a. Compose_EventType")
    pdf.code_block(""""Compose_EventType": {
  "type": "Compose",
  "inputs": "@triggerBody()?['eventType']",
  "runAfter": {}
}""")
    pdf.body_text(
        "What it does: Grabs the 'eventType' field from the webhook body.\n"
        "Example value: 'advancedsecurity.alert.created' or 'advancedsecurity.alert.statechanged'\n\n"
        "triggerBody() = the entire JSON that was POSTed to the webhook URL\n"
        "?['eventType'] = safely access the 'eventType' key (the ? means 'don't crash if missing')\n"
        "'runAfter: {}' = run immediately when the workflow starts (no dependencies)"
    )

    # AlertType
    pdf.sub_header("5b. Compose_AlertType")
    pdf.code_block(""""Compose_AlertType": {
  "type": "Compose",
  "inputs": "@coalesce(triggerBody()?['resource']?['alertType'], 'unknown')",
  "runAfter": {}
}""")
    pdf.body_text(
        "What it does: Gets the type of security alert.\n"
        "Possible values: 'secret', 'code', 'dependency'\n\n"
        "coalesce(A, B) means: 'Use A if it exists, otherwise fall back to B.'\n"
        "So if alertType is missing, we default to 'unknown' instead of crashing."
    )

    # AlertId
    pdf.sub_header("5c. Compose_AlertId")
    pdf.code_block(""""Compose_AlertId": {
  "type": "Compose",
  "inputs": "@coalesce(triggerBody()?['resource']?['alertId'],
                        triggerBody()?['resource']?['id'], 0)",
  "runAfter": {}
}""")
    pdf.body_text(
        "What it does: Gets the unique ID number for this alert.\n"
        "It tries 'alertId' first, then falls back to 'id', then to 0.\n"
        "This handles different payload versions where the field name might vary."
    )

    # RepoName
    pdf.sub_header("5d. Compose_RepoName")
    pdf.code_block(""""Compose_RepoName": {
  "type": "Compose",
  "inputs": "@coalesce(triggerBody()?['resource']?['repository']?['name'],
                        'unknown-repo')",
  "runAfter": {}
}""")
    pdf.body_text(
        "What it does: Gets the repository name where the alert was found.\n"
        "Example: 'brandsafway_Engg'"
    )

    # AlertUrl
    pdf.sub_header("5e. Compose_AlertUrl")
    pdf.code_block(""""Compose_AlertUrl": {
  "type": "Compose",
  "inputs": "@coalesce(triggerBody()?['resource']?['link'],
                        triggerBody()?['resource']?['url'], '')",
  "runAfter": {}
}""")
    pdf.body_text(
        "What it does: Gets the direct URL to view this alert in ADO.\n"
        "Tries 'link' first, then 'url'. This URL is included in the work item description "
        "so developers can click straight to the alert."
    )

    # Severity
    pdf.sub_header("5f. Compose_Severity")
    pdf.code_block(""""Compose_Severity": {
  "type": "Compose",
  "inputs": "@toLower(coalesce(triggerBody()?['resource']?['severity'],
                                'medium'))",
  "runAfter": {}
}""")
    pdf.body_text(
        "What it does: Gets the severity level and converts it to lowercase.\n"
        "Possible values: 'critical', 'high', 'medium', 'low'\n"
        "Default: 'medium' (if severity field is missing)\n\n"
        "toLower() ensures consistent comparison later (so 'High' and 'high' are treated the same)."
    )

    # FilePath
    pdf.sub_header("5g. Compose_FilePath")
    pdf.code_block(""""Compose_FilePath": {
  "type": "Compose",
  "inputs": "@coalesce(triggerBody()?['resource']?['location']?['file'],
                        triggerBody()?['resource']?['location']?['path'],
                        'N/A')",
  "runAfter": {}
}""")
    pdf.body_text(
        "What it does: Gets the file path where the vulnerability was found.\n"
        "Example: '/test-config/staging-config.env'\n"
        "Falls back to 'N/A' if no file information is available."
    )

    # LineNumber
    pdf.sub_header("5h. Compose_LineNumber")
    pdf.code_block(""""Compose_LineNumber": {
  "type": "Compose",
  "inputs": "@coalesce(triggerBody()?['resource']?['location']?['line'],
                        'N/A')",
  "runAfter": {}
}""")
    pdf.body_text(
        "What it does: Gets the exact line number of the vulnerability.\n"
        "Example: 42\n"
        "For secrets, this tells developers exactly which line to fix."
    )

    pdf.callout(
        "All 8 field extractors run IN PARALLEL (they all have 'runAfter: {}' meaning no "
        "dependencies). This makes the workflow fast - it doesn't wait for one to finish before "
        "starting the next.",
        "PERFORMANCE", pdf.GREEN
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 6: UNIQUE TAG (DEDUP)
    # ═══════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_header("6", "Building the Unique Tag (Deduplication Key)")

    pdf.body_text(
        "Before creating a work item, we need a way to check if we already created one for this "
        "same alert. Otherwise, if the webhook fires twice, we'd get duplicate tickets!\n\n"
        "The solution: create a unique tag string that combines the repo name and alert ID."
    )

    pdf.code_block(""""Compose_GhasTag": {
  "type": "Compose",
  "inputs": "@concat('GHAzDO-', outputs('Compose_RepoName'),
                     '-', string(outputs('Compose_AlertId')))",
  "runAfter": {
    "Compose_AlertId": ["Succeeded"],
    "Compose_RepoName": ["Succeeded"]
  }
}""")

    pdf.body_text(
        "What it does: Concatenates (joins) strings to create a unique tag.\n\n"
        "Example: 'GHAzDO-brandsafway_Engg-42'\n\n"
        "Notice the 'runAfter' section - this action WAITS for both Compose_AlertId and "
        "Compose_RepoName to finish first, because it needs their outputs. This is how you "
        "create dependencies between actions in a Logic App."
    )

    pdf.callout(
        "This tag is the 'fingerprint' for each alert. Later, we search ADO for work items "
        "containing this tag to avoid duplicates and to find items to close.",
        "KEY CONCEPT", pdf.ORANGE
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 7: BUILDING THE TITLE
    # ═══════════════════════════════════════════════════════════
    pdf.section_header("7", "Building the Work Item Title")

    pdf.body_text(
        "The title needs to be descriptive so developers can understand the issue at a glance. "
        "We use nested if() statements to create different titles based on the alert type."
    )

    pdf.code_block("""Logic (simplified):
IF alertType == 'secret':
    Title = "[GHAzDO-Secret] AWS Credentials detected"
ELSE IF alertType == 'code':
    Title = "[GHAzDO-CodeScan] SQL Injection vulnerability"
ELSE IF alertType == 'dependency':
    Title = "[GHAzDO-Dependency] lodash < 4.17.21 has prototype pollution"
ELSE:
    Title = "[GHAzDO-Alert] Security alert"
""")

    pdf.body_text(
        "The actual JSON uses nested if() and coalesce() expressions. Here's what each does:\n\n"
        "- For secrets: Uses 'secretType' field (e.g., 'AWS Credentials')\n"
        "- For code scanning: Uses 'title' or 'rule.description'\n"
        "- For dependencies: Uses 'title' or 'advisoryTitle'\n"
        "- Fallback: Generic 'Security alert' title\n\n"
        "The [GHAzDO-Secret] prefix makes it easy to filter and search in ADO Boards."
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 8: TAGS STRING
    # ═══════════════════════════════════════════════════════════
    pdf.section_header("8", "Building the Tags String")

    pdf.code_block(""""Compose_Tags": {
  "type": "Compose",
  "inputs": "@concat('GHAzDO;', outputs('Compose_AlertType'), ';',
                     outputs('Compose_Severity'), ';',
                     outputs('Compose_GhasTag'))",
  "runAfter": {
    "Compose_Severity": ["Succeeded"],
    "Compose_AlertType": ["Succeeded"],
    "Compose_GhasTag": ["Succeeded"]
  }
}""")

    pdf.body_text(
        "What it does: Creates a semicolon-separated tags string for the work item.\n\n"
        "Example output: 'GHAzDO;secret;critical;GHAzDO-brandsafway_Engg-42'\n\n"
        "In ADO, tags are separated by semicolons. This gives us four tags:\n"
        "  1. 'GHAzDO' - identifies all items created by this automation\n"
        "  2. 'secret' - the alert type (for filtering)\n"
        "  3. 'critical' - the severity (for prioritization)\n"
        "  4. 'GHAzDO-brandsafway_Engg-42' - the unique dedup tag"
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 9: HTML DESCRIPTION
    # ═══════════════════════════════════════════════════════════
    pdf.section_header("9", "Building the HTML Description")

    pdf.body_text(
        "The work item description is formatted as an HTML table so it looks professional in "
        "ADO Boards. It includes all the key details a developer needs to investigate the alert."
    )

    pdf.code_block("""The HTML output looks like:

+------------------+---------------------------+
| Alert Type       | secret                    |
| Severity         | critical                  |
| Repository       | brandsafway_Engg          |
| File             | /config/staging.env       |
| Line             | 5                         |
| Alert ID         | 42                        |
| Tag              | GHAzDO-brandsafway_Engg-42|
+------------------+---------------------------+

[View Alert in Azure DevOps] <-- clickable link

Auto-created by GHAzDO Logic App Integration""")

    pdf.body_text(
        "This action waits for ALL 8 field extractors to complete (notice it lists all of them "
        "in 'runAfter'). It's the most dependent action - it needs every piece of data to build "
        "the complete description."
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 10: CREATE OR CLOSE DECISION
    # ═══════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_header("10", "Deciding: Create or Close? (The Branch Point)")

    pdf.body_text(
        "This is the MOST IMPORTANT action in the entire workflow. It looks at the event type "
        "and decides which path to take:\n\n"
        "  Path A (True): Alert was CREATED -> make a new work item\n"
        "  Path B (False): Alert was RESOLVED -> close the existing work item"
    )

    pdf.sub_header("Step 10a: Check if this is a 'create' event")
    pdf.code_block(""""Compose_IsCreateEvent": {
  "type": "Compose",
  "inputs": "@or(
    equals(outputs('Compose_EventType'),
           'advancedsecurity.alert.created'),
    contains(string(outputs('Compose_EventType')), 'created')
  )",
  "runAfter": {
    "Compose_EventType": ["Succeeded"]
  }
}""")
    pdf.body_text(
        "This returns true or false.\n"
        "- or() = logical OR (if either condition is true, result is true)\n"
        "- equals() = exact string match\n"
        "- contains() = substring search (as a fallback)\n\n"
        "It's true if the event type is 'advancedsecurity.alert.created' OR contains 'created'."
    )

    pdf.sub_header("Step 10b: The Condition (If/Else Branch)")
    pdf.code_block(""""Condition_IsCreateAction": {
  "type": "If",
  "expression": {
    "and": [
      { "equals": ["@outputs('Compose_IsCreateEvent')", true] }
    ]
  },
  "actions": {
    ... (TRUE path - create work item)
  },
  "else": {
    "actions": {
      ... (FALSE path - close work item)
    }
  }
}""")
    pdf.body_text(
        "This is a standard If/Else condition. In the Logic App Designer, it shows as a "
        "diamond-shaped decision box with two branches going left (True) and right (False)."
    )

    pdf.diagram([
        "                    +------------------------+",
        "                    | Is this a CREATE event? |",
        "                    +------------------------+",
        "                     /                      \\",
        "                  YES                        NO",
        "                   /                          \\",
        "     +-------------------+         +-------------------+",
        "     | Query for dupes   |         | Find work item    |",
        "     | -> Create if new  |         | -> Close if found |",
        "     +-------------------+         +-------------------+",
    ])

    # ═══════════════════════════════════════════════════════════
    # STEP 11: CREATE PATH
    # ═══════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_header("11", "CREATE Path - Making a New Work Item")

    pdf.body_text(
        "When a new alert is created, we don't just blindly create a work item. We first CHECK "
        "if one already exists (deduplication). This prevents duplicate tickets."
    )

    pdf.sub_header("Step 11a: Query for Existing Work Items (Dedup Check)")
    pdf.code_block(""""HTTP_QueryExistingWorkItem": {
  "type": "Http",
  "inputs": {
    "uri": "https://dev.azure.com/{org}/{project}/_apis/wit/wiql?api-version=7.1",
    "method": "POST",
    "headers": {
      "Content-Type": "application/json",
      "Authorization": "Basic {base64(:PAT)}"
    },
    "body": {
      "query": "SELECT [System.Id] FROM WorkItems
                WHERE [System.Tags] CONTAINS 'GHAzDO-repoName-42'
                AND [System.State] <> 'Removed'"
    }
  }
}""")

    pdf.body_text(
        "What it does: Sends a WIQL (Work Item Query Language) query to the ADO API.\n\n"
        "WIQL is like SQL but for ADO work items. This query says:\n"
        "  'Find all work items that have our unique tag AND are not in Removed state.'\n\n"
        "The Authorization header uses Basic auth with the PAT (Personal Access Token).\n"
        "The format is: 'Basic base64(:your-pat-here)' - note the colon before the PAT!"
    )

    pdf.callout(
        "The base64(concat(':', parameters('adoPat'))) pattern is ADO's standard auth format. "
        "The colon before the PAT means 'no username, just use the token.'",
        "AUTH", pdf.PURPLE
    )

    pdf.sub_header("Step 11b: Check If Duplicates Were Found")
    pdf.code_block(""""Condition_NoExistingWorkItem": {
  "expression": {
    "and": [
      { "equals": [
        "@length(body('HTTP_QueryExistingWorkItem')?['workItems'])", 0
      ]}
    ]
  },
  "actions": {
    "HTTP_CreateWorkItem": { ... }
  },
  "else": { "actions": {} }  <-- do nothing if duplicate exists
}""")
    pdf.body_text(
        "length() counts how many results came back.\n"
        "- If 0 results: No duplicate found -> proceed to create the work item\n"
        "- If 1+ results: Duplicate exists -> do nothing (the 'else' is empty)\n\n"
        "This prevents the same alert from creating multiple tickets."
    )

    pdf.sub_header("Step 11c: Create the Work Item (HTTP PATCH)")
    pdf.code_block(""""HTTP_CreateWorkItem": {
  "type": "Http",
  "inputs": {
    "uri": "https://dev.azure.com/{org}/{project}/_apis/wit/workitems/$Issue
            ?api-version=7.1",
    "method": "PATCH",
    "headers": {
      "Content-Type": "application/json-patch+json",
      "Authorization": "Basic {base64(:PAT)}"
    },
    "body": [
      { "op": "add", "path": "/fields/System.Title",
        "value": "[GHAzDO-Secret] AWS Credentials detected" },
      { "op": "add", "path": "/fields/System.Description",
        "value": "<h3>GHAzDO Security Alert</h3>..." },
      { "op": "add", "path": "/fields/System.Tags",
        "value": "GHAzDO;secret;critical;GHAzDO-repo-42" },
      { "op": "add", "path": "/fields/Microsoft.VSTS.Common.Priority",
        "value": 1 }
    ]
  }
}""")
    pdf.body_text(
        "This is the actual API call that CREATES the work item. Key things to notice:\n\n"
        "1. METHOD is PATCH (not POST!) - ADO uses JSON Patch format for work item creation\n"
        "2. Content-Type is 'application/json-patch+json' (not regular JSON!)\n"
        "3. The body is an ARRAY of patch operations, each with:\n"
        "   - 'op': 'add' (the operation type)\n"
        "   - 'path': the field to set (like '/fields/System.Title')\n"
        "   - 'value': the value to put in that field\n\n"
        "4. Priority is set dynamically based on severity:\n"
        "   - Critical or High severity -> Priority 1 (urgent)\n"
        "   - Medium severity -> Priority 2\n"
        "   - Low severity -> Priority 3"
    )

    pdf.callout(
        "The $Issue in the URL is the work item type. It comes from the 'workItemType' parameter. "
        "You could change it to $Bug, $Task, or $User Story by changing the parameter.",
        "TIP", pdf.GREEN
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 12: CLOSE PATH
    # ═══════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_header("12", "CLOSE Path - Auto-Closing Resolved Alerts")

    pdf.body_text(
        "When GHAzDO detects that a vulnerability has been FIXED (e.g., the secret was rotated "
        "and removed from code), it fires an 'advancedsecurity.alert.statechanged' event. "
        "The workflow then auto-closes the matching work item."
    )

    pdf.sub_header("Step 12a: Find the Work Item to Close")
    pdf.code_block(""""HTTP_FindWorkItemToClose": {
  "type": "Http",
  "inputs": {
    "uri": "https://dev.azure.com/{org}/{project}/_apis/wit/wiql?api-version=7.1",
    "method": "POST",
    "body": {
      "query": "SELECT [System.Id] FROM WorkItems
                WHERE [System.Tags] CONTAINS 'GHAzDO-repoName-42'
                AND [System.State] <> 'Done'
                AND [System.State] <> 'Removed'"
    }
  }
}""")
    pdf.body_text(
        "Similar to the dedup query, but with different filters:\n"
        "- Still searches by the unique tag (GHAzDO-repoName-42)\n"
        "- Excludes items already 'Done' (already closed)\n"
        "- Excludes items in 'Removed' state (deleted)\n\n"
        "This finds only OPEN work items matching this alert."
    )

    pdf.sub_header("Step 12b: Check If We Found a Work Item")
    pdf.code_block(""""Condition_FoundWorkItemToClose": {
  "expression": {
    "and": [
      { "greater": [
        "@length(body('HTTP_FindWorkItemToClose')?['workItems'])", 0
      ]}
    ]
  }
}""")
    pdf.body_text(
        "- If 1+ results: We found an open work item -> close it\n"
        "- If 0 results: No open work item found -> do nothing\n\n"
        "This handles edge cases like alerts being resolved before a work item was ever created."
    )

    pdf.sub_header("Step 12c: Close the Work Item (Set State to Done)")
    pdf.code_block(""""HTTP_CloseWorkItem": {
  "type": "Http",
  "inputs": {
    "uri": "https://dev.azure.com/{org}/{project}/_apis/wit/workitems/{id}
            ?api-version=7.1",
    "method": "PATCH",
    "body": [
      { "op": "add",
        "path": "/fields/System.State",
        "value": "Done" },
      { "op": "add",
        "path": "/fields/System.History",
        "value": "Auto-closed: GHAzDO alert resolved/fixed." }
    ]
  }
}""")
    pdf.body_text(
        "This PATCH updates an existing work item (not creates a new one).\n\n"
        "Two things happen:\n"
        "1. State is changed to 'Done' - this closes the ticket\n"
        "2. A History comment is added explaining WHY it was closed\n\n"
        "The {id} in the URL comes from the query result:\n"
        "  body('HTTP_FindWorkItemToClose')?['workItems'][0]?['id']\n\n"
        "This grabs the ID of the first matching work item from the query results."
    )

    pdf.callout(
        "We use 'Done' (not 'Closed') because the ADO Basic process template uses Done as the "
        "final state. If your ADO project uses Agile or Scrum, you'd change this to 'Closed'.",
        "IMPORTANT", pdf.ORANGE
    )

    # ═══════════════════════════════════════════════════════════
    # STEP 13: COMPLETE FLOW DIAGRAM
    # ═══════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_header("13", "Complete Data Flow Diagram")

    pdf.body_text("Here is the complete workflow from start to finish:")

    pdf.diagram([
        "  WEBHOOK ARRIVES (ADO Service Hook sends POST)",
        "       |",
        "       v",
        "  +--------------------------------------------+",
        "  | TRIGGER: When_a_GHAzDO_alert_is_received   |",
        "  +--------------------------------------------+",
        "       |",
        "       v  (all run in PARALLEL)",
        "  +----------+  +----------+  +----------+  +----------+",
        "  | EventType|  | AlertType|  | AlertId  |  | RepoName |",
        "  +----------+  +----------+  +----------+  +----------+",
        "  +----------+  +----------+  +----------+  +----------+",
        "  | AlertUrl |  | Severity |  | FilePath |  | LineNum  |",
        "  +----------+  +----------+  +----------+  +----------+",
        "       |",
        "       v  (wait for AlertId + RepoName)",
        "  +------------------+",
        "  | GhasTag (dedup)  |  e.g. GHAzDO-repo-42",
        "  +------------------+",
        "       |",
        "       v  (wait for dependencies)",
        "  +-------+  +-------+  +-------------+  +-----------+",
        "  | Title |  | Tags  |  | Description |  | IsCreate? |",
        "  +-------+  +-------+  +-------------+  +-----------+",
        "       |",
        "       v",
        "  +============================+",
        "  | CONDITION: IsCreateAction?  |",
        "  +============================+",
        "       |                    |",
        "     TRUE                FALSE",
        "       |                    |",
        "       v                    v",
        "  +-----------+      +-----------+",
        "  | Query for |      | Find item |",
        "  | duplicates|      | to close  |",
        "  +-----------+      +-----------+",
        "       |                    |",
        "       v                    v",
        "  +-----------+      +-----------+",
        "  | No dupes? |      | Found it? |",
        "  +-----------+      +-----------+",
        "       |                    |",
        "     YES                  YES",
        "       |                    |",
        "       v                    v",
        "  +-----------+      +-----------+",
        "  | CREATE    |      | CLOSE     |",
        "  | Work Item |      | Work Item |",
        "  | (PATCH)   |      | -> Done   |",
        "  +-----------+      +-----------+",
    ])

    # ═══════════════════════════════════════════════════════════
    # STEP 14: CHEAT SHEET
    # ═══════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_header("14", "Quick Reference Cheat Sheet")

    pdf.sub_header("Key Functions Used in This Workflow")
    pdf.table_row(["Function", "What It Does"], header=True)
    pdf.table_row(["triggerBody()", "Returns the entire webhook JSON payload"])
    pdf.table_row(["?['key']", "Safely access a JSON key (returns null if missing)"])
    pdf.table_row(["coalesce(A, B)", "Returns A if not null, otherwise B (like a fallback)"])
    pdf.table_row(["concat(A, B, ...)", "Joins strings together"])
    pdf.table_row(["toLower(str)", "Converts string to lowercase"])
    pdf.table_row(["equals(A, B)", "Returns true if A equals B"])
    pdf.table_row(["or(A, B)", "Returns true if either A or B is true"])
    pdf.table_row(["contains(str, sub)", "Returns true if str contains substring sub"])
    pdf.table_row(["if(cond, T, F)", "If cond is true return T, else return F"])
    pdf.table_row(["length(array)", "Returns number of items in an array"])
    pdf.table_row(["string(val)", "Converts a value to its string representation"])
    pdf.table_row(["base64(str)", "Encodes a string as Base64 (used for auth)"])
    pdf.table_row(["outputs('Name')", "Gets the output of another action by name"])
    pdf.table_row(["body('Name')", "Gets the HTTP response body of another action"])
    pdf.table_row(["parameters('Name')", "Gets a parameter value by name"])
    pdf.ln(4)

    pdf.sub_header("Action Types Used")
    pdf.table_row(["Type", "Purpose"], header=True)
    pdf.table_row(["Request (trigger)", "Exposes an HTTP endpoint (webhook URL)"])
    pdf.table_row(["Compose", "Saves a computed value as a named variable"])
    pdf.table_row(["Http", "Makes an HTTP call to an external API (ADO REST)"])
    pdf.table_row(["If (Condition)", "Branches the workflow based on true/false"])
    pdf.ln(4)

    pdf.sub_header("ADO API Endpoints Used")
    pdf.table_row(["Endpoint", "Purpose"], header=True)
    pdf.table_row(["/_apis/wit/wiql", "Run a WIQL query to search work items"])
    pdf.table_row(["/_apis/wit/workitems/$Type", "Create a new work item (PATCH)"])
    pdf.table_row(["/_apis/wit/workitems/{id}", "Update an existing work item (PATCH)"])
    pdf.ln(4)

    pdf.sub_header("Total Action Count")
    pdf.body_text(
        "1 Trigger (HTTP Request)\n"
        "8 Compose actions (field extractors)\n"
        "1 Compose (dedup tag)\n"
        "3 Compose (title, tags, description)\n"
        "1 Compose (isCreateEvent check)\n"
        "3 HTTP actions (query, create, close)\n"
        "3 Conditions (if/else branches)\n"
        "------\n"
        "20 total actions + 1 trigger = 21 components"
    )

    # Output
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "docs", "GHAzDO-Workflow-Explainer.pdf")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    pdf.output(out)
    print(f"PDF generated: {out}")
    sz = os.path.getsize(out)
    print(f"Size: {sz:,} bytes ({sz//1024} KB)")
    print(f"Pages: {pdf.page_no()}")

if __name__ == "__main__":
    build_pdf()
