#!/usr/bin/env python3
"""
Generates a comprehensive PDF with all Q&A from the session:
1. Designer flow walkthrough (from the screenshot)
2. Why work items have 4 fields
3. Why/how tags are created
4. Full workflow explainer step-by-step
"""

from fpdf import FPDF
import os

class SessionQAPDF(FPDF):
    BLUE = (0, 120, 212)
    DARK = (30, 30, 30)
    GRAY = (100, 100, 100)
    WHITE = (255, 255, 255)
    LIGHT_BG = (245, 245, 245)
    GREEN = (16, 124, 16)
    ORANGE = (200, 100, 0)
    RED = (200, 30, 30)
    PURPLE = (100, 50, 150)

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.GRAY)
        self.cell(0, 6, "GHAzDO Workflow - Complete Q&A Guide", align="L")
        self.cell(0, 6, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.GRAY)
        self.cell(0, 10, "Confidential - Learfield Demo | Generated by Copilot CLI", align="C")

    def safe(self, text):
        return (str(text)
            .replace("\u2019", "'").replace("\u2018", "'")
            .replace("\u201c", '"').replace("\u201d", '"')
            .replace("\u2014", "--").replace("\u2013", "-")
            .replace("\u2026", "...").replace("\u2022", "*")
            .replace("\u2192", "->").replace("\u2190", "<-")
            .replace("\u2502", "|").replace("\u2500", "-")
            .replace("\u250c", "+").replace("\u2510", "+")
            .replace("\u2514", "+").replace("\u2518", "+")
            .replace("\u00b7", "*").replace("\u2588", "#")
            .replace("\u25cf", "*").replace("\u2713", "[ok]")
            .replace("\u2717", "[x]").replace("\u00a0", " ")
            .replace("\u2605", "*").replace("\u2606", "o")
            .replace("\u00d7", "x").replace("\u2248", "~=")
            .replace("\u2265", ">=").replace("\u2264", "<=")
            .replace("\u2260", "!=").replace("\u221e", "inf")
            .replace("\u00ab", "<<").replace("\u00bb", ">>")
            .replace("\u2003", " ").replace("\u2002", " "))

    def title_page(self):
        self.add_page()
        self.ln(30)
        self.set_font("Helvetica", "B", 30)
        self.set_text_color(*self.BLUE)
        self.cell(0, 14, "GHAzDO-to-ADO Workflow", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_font("Helvetica", "B", 22)
        self.cell(0, 12, "Complete Q&A Guide", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(8)
        self.set_font("Helvetica", "", 13)
        self.set_text_color(*self.DARK)
        self.cell(0, 8, "Every Question & Answer from the Live Session", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(15)

        self.set_font("Helvetica", "", 11)
        self.set_text_color(*self.GRAY)
        info = [
            ("Workflow File:", "ghazdo-to-ado.json (218 lines)"),
            ("Logic App:", "ghas-ado-sync-demo2 (Consumption tier, East US)"),
            ("ADO Org:", "brandsafway1 / brandsafway_Engg"),
            ("Service Hooks:", "2 (alert created + alert state changed)"),
            ("Successful Runs:", "3 runs, 0 failures"),
        ]
        for label, val in info:
            self.set_font("Helvetica", "B", 11)
            self.cell(45, 7, label, align="R")
            self.set_font("Helvetica", "", 11)
            self.cell(0, 7, f"  {val}", new_x="LMARGIN", new_y="NEXT")

        self.ln(15)
        self.set_draw_color(*self.BLUE)
        self.set_line_width(0.5)
        self.line(60, self.get_y(), 150, self.get_y())
        self.ln(8)

        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*self.BLUE)
        self.cell(0, 8, "What's Inside This Guide", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        sections = [
            "Q1: Show me the information flow in the designer diagram",
            "Q2: Why does the work item have so many fields?",
            "Q3: Why and how are you creating so many tags?",
            "Q4: Explain the entire ghazdo-to-ado.json file step by step",
            "Quick Reference Cheat Sheet",
        ]
        for i, s in enumerate(sections, 1):
            self.set_font("Helvetica", "", 11)
            self.set_text_color(*self.DARK)
            self.cell(8, 7, f"{i}.")
            self.cell(0, 7, s, new_x="LMARGIN", new_y="NEXT")

        self.ln(20)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(*self.GRAY)
        self.cell(0, 6, "March 2026", align="C")

    def question_banner(self, q_num, question):
        self.add_page()
        self.set_fill_color(0, 120, 212)
        self.set_text_color(*self.WHITE)
        self.set_font("Helvetica", "B", 9)
        self.cell(25, 8, f"  QUESTION {q_num}", fill=True)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, f"  {self.safe(question)}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(6)
        self.set_text_color(*self.DARK)

    def section_header(self, title, color=None):
        c = color or self.BLUE
        if self.get_y() > 245:
            self.add_page()
        self.ln(4)
        self.set_fill_color(*c)
        self.set_text_color(*self.WHITE)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 9, f"  {self.safe(title)}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_text_color(*self.DARK)

    def sub_header(self, title, color=None):
        c = color or self.BLUE
        if self.get_y() > 260:
            self.add_page()
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*c)
        self.cell(0, 7, self.safe(title), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*self.DARK)
        self.ln(1)

    def body(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.DARK)
        self.multi_cell(0, 5.5, self.safe(text), new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def code(self, code, max_lines=40):
        self.set_font("Courier", "", 8)
        self.set_fill_color(*self.LIGHT_BG)
        self.set_text_color(50, 50, 50)
        for line in code.strip().split("\n")[:max_lines]:
            if self.get_y() > 275:
                self.add_page()
                self.set_font("Courier", "", 8)
                self.set_fill_color(*self.LIGHT_BG)
                self.set_text_color(50, 50, 50)
            self.cell(0, 4.5, f"  {self.safe(line[:130])}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)
        self.set_text_color(*self.DARK)

    def callout(self, text, icon="INFO", color=None):
        c = color or self.BLUE
        if self.get_y() > 260:
            self.add_page()
        self.set_fill_color(*c)
        self.rect(10, self.get_y(), 3, 14, "F")
        self.set_x(16)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*c)
        self.cell(15, 6, f"{icon}:")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self.DARK)
        self.multi_cell(170, 5, self.safe(text), new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def table_header(self, cells, widths):
        self.set_fill_color(*self.BLUE)
        self.set_text_color(*self.WHITE)
        self.set_font("Helvetica", "B", 9)
        for i, c in enumerate(cells):
            self.cell(widths[i], 7, f" {self.safe(c)}", border=1, fill=True)
        self.ln()

    def table_row(self, cells, widths):
        if self.get_y() > 272:
            self.add_page()
        self.set_fill_color(*self.LIGHT_BG)
        self.set_text_color(*self.DARK)
        self.set_font("Helvetica", "", 9)
        for i, c in enumerate(cells):
            self.cell(widths[i], 7, f" {self.safe(c)}", border=1, fill=True)
        self.ln()

    def diagram(self, lines):
        self.set_font("Courier", "B", 8)
        self.set_text_color(*self.BLUE)
        for line in lines:
            if self.get_y() > 275:
                self.add_page()
                self.set_font("Courier", "B", 8)
                self.set_text_color(*self.BLUE)
            self.cell(0, 4.5, self.safe(line), new_x="LMARGIN", new_y="NEXT")
        self.ln(3)
        self.set_text_color(*self.DARK)

    def add_screenshot(self, path, caption=""):
        if not os.path.exists(path):
            self.body(f"[Screenshot: {path} - not found]")
            return
        if self.get_y() > 160:
            self.add_page()
        self.image(path, x=15, w=180)
        if caption:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*self.GRAY)
            self.cell(0, 5, self.safe(caption), align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_text_color(*self.DARK)
        self.ln(4)


def build_pdf():
    pdf = SessionQAPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    # ================================================================
    # TITLE PAGE
    # ================================================================
    pdf.title_page()

    # ================================================================
    # Q1: DESIGNER INFORMATION FLOW
    # ================================================================
    pdf.question_banner("1", "Show me the information flow in the designer diagram step by step")

    pdf.body(
        "The user shared a screenshot of the Logic App Designer showing the complete workflow "
        "after a successful run (all green checkmarks). Below is a layer-by-layer explanation "
        "of every box in the designer, as if you were building it from scratch."
    )

    # Add designer screenshot
    dss = os.path.join(root, "designer-ado-expanded.png")
    pdf.add_screenshot(dss, "Logic App Designer - Full Expanded View (Successful Run)")

    # Layer 1
    pdf.section_header("Layer 1: The Trigger (Top Box)")
    pdf.body(
        '"When a GHAzDO alert is received" -- This is the entry point. It creates a webhook URL '
        "that ADO Service Hooks send POST requests to whenever a security alert is created or resolved.\n\n"
        "Think of it as the front door of the workflow. Nothing happens until this URL receives a request."
    )
    pdf.callout(
        "In the Designer, this is always the topmost box. You create it by selecting "
        "'When an HTTP request is received' from the trigger list. Azure auto-generates a unique URL "
        "with a secret signature.",
        "HOW TO CREATE", pdf.GREEN
    )

    # Layer 2
    pdf.section_header("Layer 2: The 8 Parallel Field Extractors (First Row)")
    pdf.body(
        "Immediately after the trigger fires, 8 Compose actions run IN PARALLEL (side by side). "
        "Each one extracts a single piece of information from the incoming webhook JSON payload. "
        "Think of it as opening the envelope and sorting each piece of information into its own labeled folder."
    )

    w2 = [40, 45, 105]
    pdf.table_header(["Box Name", "What It Extracts", "Example Value"], w2)
    pdf.table_row(["Compose EventType", "What happened", "advancedsecurity.alert.created"], w2)
    pdf.table_row(["Compose AlertType", "Category of alert", "secret, code, or dependency"], w2)
    pdf.table_row(["Compose Severity", "How bad is it", "critical, high, medium, low"], w2)
    pdf.table_row(["Compose AlertId", "Unique alert number", "42"], w2)
    pdf.table_row(["Compose RepoName", "Which repository", "brandsafway_Engg"], w2)
    pdf.table_row(["Compose FilePath", "Which file", "/config/staging.env"], w2)
    pdf.table_row(["Compose LineNumber", "Which line", "5"], w2)
    pdf.table_row(["Compose AlertUrl", "Link to the alert", "https://dev.azure.com/..."], w2)
    pdf.ln(2)

    pdf.callout(
        "All 8 run at the SAME TIME (parallel) because they all have 'runAfter: {}' -- meaning "
        "they have no dependencies. This makes the workflow fast. In the Designer, you see them "
        "arranged in a horizontal row with lines fanning out from the trigger.",
        "PARALLEL", pdf.GREEN
    )

    pdf.body(
        "To create each one in the Designer:\n"
        "1. Click '+ New step'\n"
        "2. Search for 'Compose' and select it\n"
        "3. In the Inputs field, use the Expression tab to enter the formula\n"
        "4. Example for EventType: triggerBody()?['eventType']\n"
        "5. Rename the action (click the ... menu -> Rename)"
    )

    # Layer 3
    pdf.section_header("Layer 3: The Computed Fields (Second Row)")
    pdf.body(
        "These three boxes WAIT for specific Layer 2 boxes to finish before running. "
        "You can see the connector lines in the designer flowing down from specific extractors."
    )

    w3 = [40, 55, 95]
    pdf.table_header(["Box Name", "Waits For", "What It Builds"], w3)
    pdf.table_row(["Compose IsCreateEvent", "EventType", "true if new alert, false if resolved"], w3)
    pdf.table_row(["Compose Title", "AlertType", "[GHAzDO-Secret] AWS Credentials detected"], w3)
    pdf.table_row(["Compose GhasTag", "AlertId + RepoName", "GHAzDO-brandsafway_Engg-42 (dedup key)"], w3)
    pdf.ln(2)

    pdf.callout(
        "The GhasTag is the most important computed field -- it's the unique fingerprint that "
        "prevents duplicate work items and enables auto-closing. Format: GHAzDO-{repo}-{alertId}",
        "KEY CONCEPT", pdf.ORANGE
    )

    # Layer 4
    pdf.section_header("Layer 4: The Assembly (Third Row)")
    pdf.body(
        "These two boxes need MULTIPLE upstream boxes to finish. They assemble the final content "
        "that will go into the ADO work item."
    )

    w4 = [40, 65, 85]
    pdf.table_header(["Box Name", "Waits For", "What It Builds"], w4)
    pdf.table_row(["Compose Tags", "Severity + AlertType + GhasTag", "GHAzDO;secret;critical;GHAzDO-repo-42"], w4)
    pdf.table_row(["Compose Description", "ALL 8 extractors + GhasTag", "Full HTML table for work item body"], w4)
    pdf.ln(2)

    pdf.body(
        "In the Designer, you can see Compose Description has the most connector lines coming into it "
        "(8 dependencies) because it needs every piece of data to build the complete HTML description."
    )

    # Layer 5
    pdf.section_header("Layer 5: The Decision (Dark Diamond Box)")
    pdf.body(
        '"Condition IsCreateAction" -- This is the FORK IN THE ROAD. It checks: is this a new alert '
        "(create event) or a resolved alert (state changed event)?\n\n"
        "In the Designer, this shows as a dark box with two branches coming out of it:\n"
        "  - Left branch (green 'True' label): New alert -> Create a work item\n"
        "  - Right branch (red 'False' label): Resolved alert -> Close the work item"
    )

    pdf.diagram([
        "                      +========================+",
        "                      | Condition              |",
        "                      | IsCreateAction         |",
        "                      +========================+",
        "                       /                      \\",
        "                    TRUE                      FALSE",
        "                     /                          \\",
        "       +-------------------+         +---------------------+",
        "       | HTTP              |         | HTTP                |",
        "       | QueryExisting     |         | FindWorkItemToClose |",
        "       | WorkItem          |         |                     |",
        "       +-------------------+         +---------------------+",
        "              |                              |",
        "              v                              v",
        "       +-------------------+         +---------------------+",
        "       | Condition         |         | Condition           |",
        "       | NoExistingWorkItem|         | FoundWorkItemToClose|",
        "       +-------------------+         +---------------------+",
        "         /          \\                   /          \\",
        "       YES          NO               YES          NO",
        "        |            |                 |            |",
        "        v            v                 v            v",
        "  +-----------+   (skip)        +-----------+   (skip)",
        "  | HTTP      |                 | HTTP      |",
        "  | Create    |                 | Close     |",
        "  | WorkItem  |                 | WorkItem  |",
        "  +-----------+                 +-----------+",
    ])

    # TRUE branch detail
    pdf.sub_header("True Branch: Create Path (Left Side)")
    pdf.body(
        "Step 1: HTTP QueryExistingWorkItem -- Sends a WIQL query to ADO API: 'Do we already "
        "have a work item tagged GHAzDO-repo-42?'\n\n"
        "Step 2: Condition NoExistingWorkItem -- Checks if 0 results came back\n"
        "  - If YES (no duplicate): Proceed to create\n"
        "  - If NO (duplicate exists): Skip -- don't create a duplicate\n\n"
        "Step 3: HTTP CreateWorkItem -- Creates the actual ADO Issue with all 4 fields"
    )

    # FALSE branch detail
    pdf.sub_header("False Branch: Close Path (Right Side)")
    pdf.body(
        "Step 1: HTTP FindWorkItemToClose -- Searches for open work items with our tag\n\n"
        "Step 2: Condition FoundWorkItemToClose -- Did we find one?\n"
        "  - If YES: Close it\n"
        "  - If NO: Skip (maybe it was never created)\n\n"
        "Step 3: HTTP CloseWorkItem -- Sets state to 'Done' and adds a comment"
    )

    pdf.callout(
        "Customer talk track: 'The entire flow runs in under 2 seconds. Developers see the work "
        "item in their sprint board within seconds of a vulnerability being detected. When they fix "
        "it, the ticket auto-closes. Zero manual work.'",
        "TALK TRACK", pdf.PURPLE
    )

    # ================================================================
    # Q2: WHY SO MANY FIELDS IN WORK ITEM
    # ================================================================
    pdf.question_banner("2", "Why does the work item have so many fields?")

    # Add the code screenshot
    cs1 = os.path.join(root, "code-view-ado-pasted.png")
    pdf.add_screenshot(cs1, "HTTP_CreateWorkItem action in Code View")

    pdf.body(
        "The HTTP_CreateWorkItem action uses the ADO REST API to create a work item. "
        "ADO requires a specific format called 'JSON Patch' -- each field you want to set "
        "is a separate operation in an array.\n\n"
        "The body has exactly 4 patch operations. Here's why each one is necessary:"
    )

    pdf.section_header("The 4 Fields Explained")

    # Field 1: Title
    pdf.sub_header("Field 1: System.Title (The Headline)", pdf.BLUE)
    pdf.code("""{ "op": "add", "path": "/fields/System.Title",
  "value": "@{outputs('Compose_Title')}" }""")
    pdf.body(
        "What it sets: The work item title -- the first thing anyone sees.\n\n"
        "Example values:\n"
        "  - [GHAzDO-Secret] AWS Credentials detected\n"
        "  - [GHAzDO-CodeScan] SQL Injection vulnerability\n"
        "  - [GHAzDO-Dependency] lodash < 4.17.21 has prototype pollution\n\n"
        "Why it's needed: Without a title, the work item would be blank. "
        "The [GHAzDO-*] prefix makes it instantly recognizable in the backlog."
    )

    # Field 2: Description
    pdf.sub_header("Field 2: System.Description (The Details)", pdf.BLUE)
    pdf.code("""{ "op": "add", "path": "/fields/System.Description",
  "value": "@{outputs('Compose_Description')}" }""")
    pdf.body(
        "What it sets: A rich HTML table in the work item body containing:\n"
        "  - Alert Type (secret / code / dependency)\n"
        "  - Severity (critical / high / medium / low)\n"
        "  - Repository name\n"
        "  - File path where the issue was found\n"
        "  - Line number\n"
        "  - Alert ID\n"
        "  - Dedup tag\n"
        "  - Clickable link to view the alert directly in ADO\n\n"
        "Why it's needed: Gives the developer ALL the context they need to investigate "
        "and fix the issue without leaving the work item."
    )

    # Field 3: Tags
    pdf.sub_header("Field 3: System.Tags (Filtering & Dedup)", pdf.BLUE)
    pdf.code("""{ "op": "add", "path": "/fields/System.Tags",
  "value": "@{outputs('Compose_Tags')}" }""")
    pdf.body(
        "What it sets: A semicolon-separated string of 4 tags.\n"
        "Example: 'GHAzDO;secret;critical;GHAzDO-brandsafway_Engg-42'\n\n"
        "Why it's needed: Tags serve THREE critical purposes:\n"
        "  1. Filtering: Find all auto-created items in ADO Boards\n"
        "  2. Triaging: Filter by severity or alert type\n"
        "  3. Deduplication: The unique tag prevents duplicate tickets\n\n"
        "(See Question 3 below for a deep dive on tags)"
    )

    # Field 4: Priority
    pdf.sub_header("Field 4: Microsoft.VSTS.Common.Priority (Urgency)", pdf.BLUE)
    pdf.code("""{ "op": "add", "path": "/fields/Microsoft.VSTS.Common.Priority",
  "value": "@if(or(equals(outputs('Compose_Severity'),'critical'),
                    equals(outputs('Compose_Severity'),'high')),
               1,
               if(equals(outputs('Compose_Severity'),'medium'), 2, 3))" }""")
    pdf.body(
        "What it sets: The priority number (1 = highest, 4 = lowest).\n\n"
        "The mapping:\n"
        "  - Critical or High severity -> Priority 1 (urgent -- fix immediately)\n"
        "  - Medium severity -> Priority 2 (fix soon)\n"
        "  - Low severity -> Priority 3 (fix when convenient)\n\n"
        "Why it's needed: Automatically triages the work item so the most dangerous "
        "vulnerabilities get attention first. No human needs to manually set priority."
    )

    pdf.callout(
        "These are the MINIMUM VIABLE FIELDS. You could add more (like Assigned To, Area Path, "
        "Iteration Path), but these 4 give you a fully functional, searchable, prioritized work item.",
        "WHY ONLY 4?", pdf.GREEN
    )

    # API format explanation
    pdf.section_header("Why PATCH Instead of POST?")
    pdf.body(
        "You might wonder: 'Why is the method PATCH for creating a new item?'\n\n"
        "This is an ADO API quirk. The ADO Work Items API uses JSON Patch format (RFC 6902) "
        "for BOTH creating and updating work items. The key differences:\n\n"
        "  Creating: PATCH to /_apis/wit/workitems/$Issue  (no ID in URL)\n"
        "  Updating: PATCH to /_apis/wit/workitems/{id}   (ID in URL)\n\n"
        "The Content-Type must be 'application/json-patch+json' (not regular 'application/json'). "
        "If you use the wrong Content-Type, ADO returns a 415 error."
    )

    pdf.section_header("The Authorization Header")
    pdf.code(""""Authorization": "Basic @{base64(concat(':', parameters('adoPat')))}" """)
    pdf.body(
        "This constructs Basic authentication using the PAT:\n"
        "  1. concat(':', PAT) -- prepends a colon (ADO format: no username, just token)\n"
        "  2. base64(...) -- encodes the string as Base64\n"
        "  3. 'Basic ...' -- the standard HTTP Basic auth header format\n\n"
        "The PAT (Personal Access Token) is stored as a SecureString parameter, "
        "so it's encrypted at rest and never visible in run history logs."
    )

    # ================================================================
    # Q3: WHY SO MANY TAGS
    # ================================================================
    pdf.question_banner("3", "Why and how are you creating so many tags?")

    pdf.body(
        "The Compose_Tags action creates a SINGLE STRING with 4 tags separated by semicolons. "
        "In ADO, semicolons are the tag delimiter, so this one string becomes 4 separate tags "
        "on the work item."
    )

    pdf.section_header("The Tag Formula")
    pdf.code(""""Compose_Tags": {
  "inputs": "@concat('GHAzDO;',
                     outputs('Compose_AlertType'), ';',
                     outputs('Compose_Severity'), ';',
                     outputs('Compose_GhasTag'))"
}

Example output: "GHAzDO;secret;critical;GHAzDO-brandsafway_Engg-42"
                 ^       ^       ^        ^
                 Tag 1   Tag 2   Tag 3    Tag 4""")

    pdf.section_header("Each Tag Explained")

    # Tag 1
    pdf.sub_header("Tag 1: 'GHAzDO' -- The Automation Marker", pdf.GREEN)
    pdf.body(
        "Purpose: Identifies ALL work items created by this automation.\n\n"
        "Use case: Go to ADO Boards, filter by tag 'GHAzDO', and instantly see every "
        "security-related work item that was auto-created. This separates automated tickets "
        "from manually created ones.\n\n"
        "This is always the same fixed string -- every auto-created work item gets it."
    )

    # Tag 2
    pdf.sub_header("Tag 2: Alert Type (e.g., 'secret') -- The Category", pdf.ORANGE)
    pdf.body(
        "Purpose: Classifies the type of security alert.\n\n"
        "Possible values:\n"
        "  - 'secret' -- exposed credentials (API keys, passwords, tokens)\n"
        "  - 'code' -- code scanning findings (SQL injection, XSS, etc.)\n"
        "  - 'dependency' -- vulnerable dependencies (npm packages, NuGet, etc.)\n\n"
        "Use case: Filter your board to see ONLY secret alerts, or ONLY dependency alerts. "
        "Useful when different teams handle different types of vulnerabilities."
    )

    # Tag 3
    pdf.sub_header("Tag 3: Severity (e.g., 'critical') -- The Urgency", pdf.RED)
    pdf.body(
        "Purpose: Shows how severe the vulnerability is.\n\n"
        "Possible values:\n"
        "  - 'critical' -- must fix immediately (e.g., production API key exposed)\n"
        "  - 'high' -- fix urgently (e.g., SQL injection vulnerability)\n"
        "  - 'medium' -- fix soon (e.g., outdated dependency with known CVE)\n"
        "  - 'low' -- fix when convenient (e.g., informational finding)\n\n"
        "Use case: Create a dashboard query: 'Show all critical GHAzDO items' for security standups."
    )

    # Tag 4
    pdf.sub_header("Tag 4: Unique Fingerprint (e.g., 'GHAzDO-brandsafway_Engg-42')", pdf.PURPLE)
    pdf.body(
        "Purpose: The MOST IMPORTANT tag -- serves as the unique identifier for deduplication "
        "and auto-closing.\n\n"
        "Format: GHAzDO-{repository_name}-{alert_id}\n"
        "Example: GHAzDO-brandsafway_Engg-42\n\n"
        "How it's used:\n\n"
        "1. DEDUPLICATION (preventing duplicates):\n"
        "   Before creating a new work item, the workflow runs a WIQL query:\n"
        "   'SELECT [System.Id] FROM WorkItems WHERE [System.Tags]\n"
        "    CONTAINS GHAzDO-brandsafway_Engg-42'\n"
        "   If it finds a match, it SKIPS creation -- no duplicate ticket.\n\n"
        "2. AUTO-CLOSING (matching resolved alerts to tickets):\n"
        "   When GHAzDO says alert #42 is resolved, the workflow searches:\n"
        "   'Find the open work item tagged GHAzDO-brandsafway_Engg-42'\n"
        "   Then it sets its state to 'Done' automatically.\n\n"
        "   Without this unique tag, there would be NO WAY to link an incoming\n"
        "   webhook back to the correct work item."
    )

    pdf.callout(
        "Think of Tag 4 as a license plate number. Every car (work item) has a unique plate "
        "(tag) so you can find it in a parking lot (backlog) of thousands of items.",
        "ANALOGY", pdf.GREEN
    )

    pdf.section_header("Why Not Just Use the Title for Dedup?")
    pdf.body(
        "Good question! Titles can be edited by users, and title matching is fragile "
        "(case sensitivity, special characters, truncation). Tags are:\n\n"
        "  1. Immutable (users rarely edit tags)\n"
        "  2. Searchable via WIQL CONTAINS operator\n"
        "  3. Exact match (no fuzzy matching issues)\n"
        "  4. Visible in the ADO UI for easy debugging\n\n"
        "The tag approach is the industry standard for automated work item management."
    )

    # Visual example of how tags appear in ADO
    pdf.section_header("How Tags Appear in ADO Boards")
    pdf.code("""
+------------------------------------------------------------------+
|  Issue #1234                                            Priority 1|
|  [GHAzDO-Secret] AWS Credentials detected                        |
|                                                                   |
|  Tags: [GHAzDO] [secret] [critical] [GHAzDO-brandsafway_Engg-42] |
|                                                                   |
|  State: New          Assigned: unassigned                         |
+------------------------------------------------------------------+

In ADO Boards, each tag appears as a colored pill/badge on the card.
You can click any tag to filter the board to show only matching items.
""")

    # ================================================================
    # Q4: FULL WORKFLOW EXPLAINER
    # ================================================================
    pdf.question_banner("4", "Explain the entire ghazdo-to-ado.json file like I'm a newbie")

    pdf.section_header("What This File IS")
    pdf.body(
        "This is a Logic App Workflow Definition -- a JSON file that tells Azure Logic Apps "
        "what to do step by step. It's like a recipe:\n\n"
        "  - The TRIGGER is the 'start cooking' signal\n"
        "  - The ACTIONS are the cooking steps\n"
        "  - The CONDITIONS are 'if the sauce is too thick, add water'\n"
        "  - The PARAMETERS are the ingredients list\n\n"
        "The file has 218 lines and contains 1 trigger + 20 actions = 21 total components."
    )

    pdf.section_header("The Big Picture (30-Second Version)")
    pdf.diagram([
        "  +-----------+     +-----------+     +------------+",
        "  | GHAzDO    | --> | ADO       | --> | Logic App  |",
        "  | detects a |     | Service   |     | runs this  |",
        "  | vuln      |     | Hook      |     | workflow   |",
        "  +-----------+     +-----------+     +------------+",
        "                                           |",
        "                        +------------------+------------------+",
        "                        |                                     |",
        "                  [New alert?]                         [Resolved?]",
        "                        |                                     |",
        "                        v                                     v",
        "               +----------------+                   +----------------+",
        "               | Create ADO     |                   | Close ADO      |",
        "               | Work Item      |                   | Work Item      |",
        "               | (Issue)        |                   | (-> Done)      |",
        "               +----------------+                   +----------------+",
    ])

    # Section: Schema
    pdf.section_header("Part 1: The File Header (Lines 1-3)")
    pdf.code("""{
  "$schema": "https://schema.management.azure.com/.../workflowdefinition.json#",
  "contentVersion": "1.0.0.0",""")
    pdf.body(
        "These two lines are boilerplate -- like the DOCTYPE in HTML. They tell Azure:\n"
        "  - $schema: 'This is a Logic App workflow file, validate it against this spec'\n"
        "  - contentVersion: 'This is version 1.0.0.0 of this workflow'\n\n"
        "You never need to change these. Azure adds them automatically."
    )

    # Section: Parameters
    pdf.section_header("Part 2: Parameters (Lines 4-9)")
    pdf.code(""""parameters": {
  "adoOrganization": { "type": "String" },
  "adoProject":      { "type": "String" },
  "adoPat":          { "type": "SecureString" },
  "workItemType":    { "type": "String", "defaultValue": "Issue" }
}""")

    w_param = [40, 30, 120]
    pdf.table_header(["Parameter", "Type", "What It Is"], w_param)
    pdf.table_row(["adoOrganization", "String", "Your ADO org (e.g., 'brandsafway1')"], w_param)
    pdf.table_row(["adoProject", "String", "The project name (e.g., 'brandsafway_Engg')"], w_param)
    pdf.table_row(["adoPat", "SecureString", "Personal Access Token (encrypted, never logged)"], w_param)
    pdf.table_row(["workItemType", "String", "Type of ticket to create (default: 'Issue')"], w_param)
    pdf.ln(2)
    pdf.body(
        "Parameters are set ONCE when deploying. They let you reuse the same workflow "
        "for different ADO orgs without editing the JSON. Reference them with: parameters('name')"
    )

    # Section: Trigger
    pdf.section_header("Part 3: The Trigger (Lines 10-16)")
    pdf.code(""""triggers": {
  "When_a_GHAzDO_alert_is_received": {
    "type": "Request",
    "kind": "Http",
    "inputs": { "schema": {} }
  }
}""")
    pdf.body(
        "This creates an HTTP endpoint (webhook URL). When ADO sends a POST to this URL, "
        "the workflow runs.\n\n"
        "The 'schema: {}' means we accept any JSON body without validation. We use coalesce() "
        "in the Compose actions to safely handle missing fields."
    )

    # Section: Field Extractors
    pdf.section_header("Part 4: Field Extractors (Lines 17-57)")
    pdf.body(
        "Eight Compose actions run in parallel, each extracting one field from the webhook payload:"
    )

    w_ext = [40, 75, 75]
    pdf.table_header(["Action", "Expression", "Default If Missing"], w_ext)
    pdf.table_row(["EventType", "triggerBody()?['eventType']", "(null)"], w_ext)
    pdf.table_row(["AlertType", "coalesce(resource.alertType, ...)", "'unknown'"], w_ext)
    pdf.table_row(["AlertId", "coalesce(resource.alertId, resource.id, ...)", "0"], w_ext)
    pdf.table_row(["RepoName", "coalesce(resource.repository.name, ...)", "'unknown-repo'"], w_ext)
    pdf.table_row(["AlertUrl", "coalesce(resource.link, resource.url, ...)", "'' (empty)"], w_ext)
    pdf.table_row(["Severity", "toLower(coalesce(resource.severity, ...))", "'medium'"], w_ext)
    pdf.table_row(["FilePath", "coalesce(resource.location.file, ...path)", "'N/A'"], w_ext)
    pdf.table_row(["LineNumber", "coalesce(resource.location.line, ...)", "'N/A'"], w_ext)
    pdf.ln(2)

    pdf.callout(
        "coalesce(A, B, C) = 'Try A first. If null, try B. If null, use C.' This makes the "
        "workflow resilient -- it won't crash even if the webhook payload is missing some fields.",
        "KEY FUNCTION", pdf.ORANGE
    )

    # Section: Computed fields
    pdf.section_header("Part 5: Computed Fields (Lines 58-95)")
    pdf.body(
        "Four more Compose actions that COMBINE the extracted fields into structured data:\n\n"
        "1. GhasTag: concat('GHAzDO-', RepoName, '-', AlertId) -> unique dedup key\n"
        "2. Title: nested if() to create type-specific titles (see Question 2)\n"
        "3. Tags: concat all 4 tags with semicolons (see Question 3)\n"
        "4. Description: HTML table with all alert details and clickable link"
    )

    # Section: Decision
    pdf.section_header("Part 6: The Decision Branch (Lines 96-215)")
    pdf.body(
        "This is where the real logic happens. Two nested checks:\n\n"
        "First: Compose_IsCreateEvent checks if eventType contains 'created'\n"
        "Then: Condition_IsCreateAction branches into True (create) or False (close)\n\n"
        "TRUE PATH (new alert detected):\n"
        "  1. HTTP_QueryExistingWorkItem -- WIQL search for duplicates\n"
        "  2. Condition_NoExistingWorkItem -- If no dupe, proceed\n"
        "  3. HTTP_CreateWorkItem -- PATCH to ADO API to create Issue\n\n"
        "FALSE PATH (alert resolved/fixed):\n"
        "  1. HTTP_FindWorkItemToClose -- WIQL search for open matching item\n"
        "  2. Condition_FoundWorkItemToClose -- If found, proceed\n"
        "  3. HTTP_CloseWorkItem -- PATCH to set state='Done' + add comment"
    )

    # Section: Complete data flow
    pdf.section_header("Complete Data Flow (All 21 Components)")
    pdf.diagram([
        "  WEBHOOK ARRIVES (ADO Service Hook sends POST request)",
        "       |",
        "       v",
        "  +----------------------------------------------+",
        "  | TRIGGER: When_a_GHAzDO_alert_is_received     |",
        "  +----------------------------------------------+",
        "       |",
        "       v  (8 actions run in PARALLEL -- all at once)",
        "  +----------+ +----------+ +----------+ +----------+",
        "  |EventType | |AlertType | |Severity  | |AlertId   |",
        "  +----------+ +----------+ +----------+ +----------+",
        "  +----------+ +----------+ +----------+ +----------+",
        "  |RepoName  | |FilePath  | |LineNumber| |AlertUrl  |",
        "  +----------+ +----------+ +----------+ +----------+",
        "       |",
        "       v  (wait for AlertId + RepoName)",
        "  +------------------+",
        "  | GhasTag (dedup)  |  e.g. GHAzDO-repo-42",
        "  +------------------+",
        "       |",
        "       v  (build outputs from multiple inputs)",
        "  +-------+ +-------+ +-------------+ +-----------+",
        "  | Title | | Tags  | | Description | | IsCreate? |",
        "  +-------+ +-------+ +-------------+ +-----------+",
        "       |",
        "       v",
        "  +=============================+",
        "  | CONDITION: IsCreateAction?   |  <-- THE FORK",
        "  +=============================+",
        "       |                    |",
        "     TRUE                FALSE",
        "       |                    |",
        "       v                    v",
        "  +-----------+      +---------------+",
        "  | Query for |      | Find item     |",
        "  | duplicates|      | to close      |",
        "  +-----------+      +---------------+",
        "       |                    |",
        "       v                    v",
        "  +-----------+      +---------------+",
        "  | No dupes? |      | Found it?     |",
        "  +-----------+      +---------------+",
        "     YES                  YES",
        "       |                    |",
        "       v                    v",
        "  +-----------+      +---------------+",
        "  | CREATE    |      | CLOSE         |",
        "  | Work Item |      | Work Item     |",
        "  | (PATCH)   |      | -> Done       |",
        "  +-----------+      +---------------+",
    ])

    # ================================================================
    # CHEAT SHEET
    # ================================================================
    pdf.question_banner("REF", "Quick Reference Cheat Sheet")

    pdf.section_header("Key Functions Used")
    w_fn = [50, 140]
    pdf.table_header(["Function", "What It Does"], w_fn)
    pdf.table_row(["triggerBody()", "Returns the entire webhook JSON payload"], w_fn)
    pdf.table_row(["?['key']", "Safely access a JSON key (null if missing, no crash)"], w_fn)
    pdf.table_row(["coalesce(A, B, C)", "Returns first non-null value (fallback chain)"], w_fn)
    pdf.table_row(["concat(A, B, ...)", "Joins strings together into one string"], w_fn)
    pdf.table_row(["toLower(str)", "Converts to lowercase for consistent comparison"], w_fn)
    pdf.table_row(["equals(A, B)", "Returns true if A exactly equals B"], w_fn)
    pdf.table_row(["or(A, B)", "Returns true if either A or B is true"], w_fn)
    pdf.table_row(["contains(str, sub)", "Returns true if str contains the substring sub"], w_fn)
    pdf.table_row(["if(cond, T, F)", "If condition is true return T, else return F"], w_fn)
    pdf.table_row(["length(array)", "Returns number of items in an array (for dedup check)"], w_fn)
    pdf.table_row(["string(val)", "Converts a value to string (e.g., number -> text)"], w_fn)
    pdf.table_row(["base64(str)", "Encodes string as Base64 (used for auth headers)"], w_fn)
    pdf.table_row(["outputs('Name')", "Gets the output value of another Compose action"], w_fn)
    pdf.table_row(["body('Name')", "Gets the HTTP response body of an HTTP action"], w_fn)
    pdf.table_row(["parameters('Name')", "Gets a configured parameter value"], w_fn)
    pdf.ln(4)

    pdf.section_header("Action Types Used")
    w_at = [50, 140]
    pdf.table_header(["Type", "Purpose"], w_at)
    pdf.table_row(["Request (trigger)", "Exposes an HTTP endpoint -- the webhook URL"], w_at)
    pdf.table_row(["Compose", "Saves a computed value as a named variable"], w_at)
    pdf.table_row(["Http", "Makes an HTTP request to ADO REST API"], w_at)
    pdf.table_row(["If (Condition)", "Branches the workflow into True/False paths"], w_at)
    pdf.ln(4)

    pdf.section_header("ADO REST API Endpoints Used")
    w_ep = [65, 55, 70]
    pdf.table_header(["Endpoint", "Method", "Purpose"], w_ep)
    pdf.table_row(["/_apis/wit/wiql", "POST", "Run WIQL query to search work items"], w_ep)
    pdf.table_row(["/_apis/wit/workitems/$Type", "PATCH", "Create a new work item"], w_ep)
    pdf.table_row(["/_apis/wit/workitems/{id}", "PATCH", "Update existing work item"], w_ep)
    pdf.ln(4)

    pdf.section_header("Component Summary")
    pdf.body(
        "1 Trigger (HTTP Request webhook)\n"
        "8 Compose actions (parallel field extractors)\n"
        "1 Compose (dedup tag -- GhasTag)\n"
        "3 Compose (title, tags, description)\n"
        "1 Compose (isCreateEvent boolean check)\n"
        "3 HTTP actions (query dupes, create item, close item)\n"
        "3 Conditions (create-or-close, no-dupe, found-to-close)\n"
        "---\n"
        "20 total actions + 1 trigger = 21 components\n"
        "Total execution time: < 2 seconds\n"
        "Cost per run: fractions of a cent (Consumption tier)"
    )

    # Output
    out_path = os.path.join(root, "docs", "GHAzDO-Workflow-Complete-QA-Guide.pdf")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    pdf.output(out_path)
    sz = os.path.getsize(out_path)
    print(f"PDF generated: {out_path}")
    print(f"Size: {sz:,} bytes ({sz // 1024} KB)")
    print(f"Pages: {pdf.page_no()}")

if __name__ == "__main__":
    build_pdf()
